[WIP] 카카오 로그인 구현
GAME-EE/client pull request #65
Opened 2022-09-05 12:58 UTC by bae-sh

- Closes #63 
- Closes #64

2022-10-06 14:06 UTC, bae-sh reviewed
카카오 로그인 구현

2022-10-06 14:06 UTC, bae-sh commented on src/api/index.tsx
> +};
user의 정보를 서버에서 받아오는 함수

2022-10-06 14:06 UTC, bae-sh commented on src/api/index.tsx
> +};
refresh Token은 존재하지만 access Token이 만료 될 경우 서버에 토큰 쿠키를 요청하는 함수

2022-10-06 14:06 UTC, bae-sh commented on src/pages/_app.tsx
> +};
next-js에서 쿠키를 받아오기 위해서 next-cookies 라이브러리를 사용하였고 실행 전 data를 fetching 하기 위해 react 에서 useEffect와 같이 nextJs에서 `getInitialProps`를 이용하여 ctx를 받아왔다. next v9 이상에서는 getInitialProps 대신 getStaticProps, getStaticPaths, getServerSideProps을 사용하도록 가이드 한다고 한다.

2022-10-06 14:06 UTC, bae-sh commented on src/pages/index.tsx
> +  }, [pageProps, setTokenState]);
쿠키에 refreshToken이 존재할 경우 localStorage에 저장. 없을경우 localStorage에 있는지 확인하고 있을경우 클라이언트 상태에 refreshToken을 저장

2022-10-06 14:06 UTC, bae-sh commented on src/pages/index.tsx
> +
refresh Token 이 존재하고 Access가 없는경우 서버로 부터 Access 토큰 쿠키을 받아온다. Access 토큰 쿠키가 있을 경우에는 유저 상태를 받아오고 recoil에 저장한다.

2022-10-06 14:23 UTC, sumi-0011 commented on src/pages/_app.tsx
> +};
혹시 `allCookies['access_token'] || ''` 이랑 `allCookies['access_token'] ?? ''` 은 다른 코드일까요?

2022-10-06 14:33 UTC, sumi-0011 requested changes
`src/pages/index.tsx` 파일에 있는 
이번에 추가된 user관련과 token관련 로직들은 매핑해서 분리를 하면 더 좋을거같아요!

2022-10-06 14:33 UTC, sumi-0011 commented on src/api/url.ts
> +const GET_USER_PROFILE = 'http://localhost:4000/api/user/profile';
url 앞에 `http://localhost:4000/api/` 은 다른 변수에 저장해서 사용하면 좋을거같아요!
서버에서 변경사항이 생겨 해당 url 이 종종 바뀌는 경우가 있더라구요. 
그럴때 baseURL을 한번에 바꿀수 있도록!

2022-10-06 14:33 UTC, sumi-0011 commented on src/atom.ts
> +});
id, nickname, name등을 따로 null처리 한건,
userState를 사용하는 부분에서 값이 없는지를 확인하기 위해 null 체크를 해서인가요?

id 같은 경우에는 number 타입이니까 0으로 , name은 string 이니까 `''`으로 초기화 하면 되는데 그렇게 하지 않은 이유가 있나 궁금해요

2022-10-06 16:26 UTC, bae-sh commented on src/pages/_app.tsx
> +};
음 나도 헷갈려서 찾아봤는데 `||` 이것은 논리 연산자 이고 `??`이것은 null 병합 연산자라고 하네
`??` 연산자가 나오기 전에는 `||` 연산자를 사용했었는데 `||` 의 경우 좌항이 false로 판단 되는 값이면 우항 값을 반환하거든.
그런데 이때 0값 또는 ' ' 값도 JS 에서는 false로 판단하기 때문에 의도치 않은 동작이 발생할수 있고  따라서  `??`연산자를 사용을 지향하는거 같아
`??`연산자는 `null` 또는 `undefined` 일 경우만 우항을 반환하기 떄문에 위의 케이스에 더 알맞는 방식인거같다 ㅎㅎ 굿 캐치!!👍

2022-10-06 16:26 UTC, bae-sh commented on src/api/url.ts
> +const GET_USER_PROFILE = 'http://localhost:4000/api/user/profile';
아 그러면 더 좋을거 같다 !! 수정해볼게 ㅎㅎ

2022-10-06 16:31 UTC, bae-sh commented on src/atom.ts
> +});
atom에서 프로퍼티 값을 초기화 해줘야 하는데 id에 `0`이 들어가면 혹시나 id값이 0인 유저가 있을수도 있지 않을까? 비슷한 이유로 string에 `' '` 값이 들어가게 되면 name에도 값이 존재한다고 판단했거든. 
명확하게 초기화 되어있고 유저를 받지 못한 상태를 알리기 위해서 나는 null을 사용했어!

2022-10-07 15:42 UTC, junghyeonsu approved these changes
고생했어 성현!

2022-10-08 03:57 UTC, bae-sh commented on src/api/url.ts
> +const GET_USER_PROFILE = 'http://localhost:4000/api/user/profile';
수정완료!

2022-10-08 03:57 UTC, bae-sh commented on src/pages/_app.tsx
> +};
수정완료!

2022-10-08 04:02 UTC, sumi-0011 approved these changes
고생하셨습니다 :D

2022-10-08 04:02 UTC, sumi-0011 commented on src/api/url.ts
> +const GET_USER_PROFILE = `${baseURL}/user/profile`;
👍

2022-10-08 04:02 UTC, sumi-0011 commented on src/pages/_app.tsx
> +  const accessToken = allCookies['access_token'] ?? '';
👍

2022-10-08 04:11 UTC, bae-sh commented
#65 카카로 로그인 구현 입니다.

2022-10-08 04:11 UTC, merged